### ISSUE TITLE
Wrong kubectl command at "Manage cluster" user guide

### ISSUE THREAD

**Issue by yaohui-wyh** [nocalhost/nocalhost.github.io#187]
Link:
https://nocalhost.dev/docs/guides/manage-cluster

![image](https://user-images.githubusercontent.com/3115235/159640694-a2dc5eec-e5f0-4f50-a635-3660aa5942a0.png)

Command should be 
`kubectl config view --minify --raw --flatten` instead of `kubectl config view --minify --raw --flattern`

**Comment by yuanganping** [comment]
Thanks for your feedback
@yaohui-wyh
